server:
  port: 10002
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: admin
    password: admin
logging:
  level:
    org.springframework.transaction: trace
    pl.training: DEBUG
