POST http://localhost:8080/payments
Accept: application/json
Content-Type: application/json

{
  "value": "50 PLN",
  "additionalInfo": {
    "cardNumber": "1234567890",
    "cvv": 255
  }
}

###

GET  http://localhost:8080/payments/05cc34de-a01c-4661-9308-c75d7f04b523
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/orders
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "entries": {
    "1": 2
  }
}

###

GET http://localhost:8888/application-default.yml

###

GET http://localhost:8888/application-default.properties

###

GET http://localhost:8888/application-development.yml

###

GET http://localhost:8888/shop-service-default.yml

###

GET http://localhost:8888/shop-service-development.yml
