POST http://localhost:8080/payments
Accept: application/json
Content-Type: application/json

{
  "value": "50 PLN",
  "additionalInfo": {
    "cardNumber": "1234567890",
    "cvv": 255
  }
}

###

GET  http://localhost:8080/payments/05cc34de-a01c-4661-9308-c75d7f04b523
Accept: application/json
Content-Type: application/json
