spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: development
  cloud:
    config:
      label: 004-Config-Discovery-Gateway-servers
